services:
  # API
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      #End user does not have to configure these
      - MONGODB_URL=mongodb://mongodb:27017/yourdb  
      - MONGODB_DATABASE=yourdb
      - MONGODB_COLLECTION=items
    depends_on:
      mongodb:
        condition: service_started
      model-service:
        condition: service_healthy
    networks:
      - app-network
  
  # MongoDB   
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  # Only for host machine access
    environment:
      #This creates a default database so the enduser doesn't have to configure it manualy
      MONGO_INITDB_DATABASE: yourdb
    volumes:
      - mongodb_data:/data/db
      - ./api/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
  
  # Frontend 
  frontend:
    build: ./front-end
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

#Model Service
  model-service:
    build: ./model_service
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network
# Define the network
networks:
  app-network:
    #Custom docker bridge network
    driver: bridge

# Define volumes
volumes:
  mongodb_data: