//Code generated by Microsoft Copilot for initial start.
// MongoDB initialization script
// This runs automatically when the MongoDB container starts for the first time

// Switch to your database
db = db.getSiblingDB('yourdb');

// Create collections
db.createCollection('items');

// Create indexes for better performance
db.items.createIndex({ "name": 1 });        // For name searches
db.items.createIndex({ "price": 1 });       // For price filtering
db.items.createIndex({ "name": 1, "price": -1 }); // Compound index

// Optional: Seed with sample data
// db.items.insertMany([
//   {
//     name: "Laptop",
//     price: 999.99,
//     description: "High-performance laptop for development"
//   },
//   {
//     name: "Mouse",
//     price: 29.99,
//     description: "Wireless ergonomic mouse"
//   },
//   {
//     name: "Keyboard",
//     price: 79.99,
//     description: "Mechanical keyboard with RGB lighting"
//   }
// ]);

print("✅ Database and collections initialized successfully!");
print(`📊 Created ${db.items.countDocuments()} sample items`);